apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eneczjs2f-python
  janus-idp.io/tekton: eneczjs2f-python
  backstage.io/kubernetes-id: eneczjs2f-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eneczjs2f-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
